---
title: "Multidimensional Dataset Vignette"
author: "Sam"
date: "9/6/2018"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Multidimensional verification}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
Sys.setenv('RETICULATE_PYTHON'='/anaconda/bin/python')
library(rhdf5client2)
library(reticulate)
```

## Access to multi-dimensional dataset:

### Get result with `rhdf5client2`

```{r}
src <- Source('http://hsdshdflab.hdfgroup.org')
rd <- Dataset(File(src, '/home/spollack/testzero.h5'), '/grpC/dset4d')
A <- getData(rd, list(3:4, 8:9, 5:6, 2:3))
sum(A)
```

### Get result with `reticulate` and `h5pyd`

```{r}
h5pyd <- import("h5pyd")
builtins <- import_builtins()

endpoint <- 'http://hsdshdflab.hdfgroup.org'
domain <- '/home/spollack/testzero.h5'
f <- h5pyd$File(endpoint=endpoint, mode='r', domain=domain)
pd <- f$`__getitem__`('/grpC/dset4d')
scs <- tuple(builtins$slice(2L, 4L, 1L), builtins$slice(7L, 9L, 1L), 
             builtins$slice(4L, 6L, 1L), builtins$slice(1L, 3L, 1L))
A <- pd$`__getitem__`(scs)
sum(A)   
```

## Special Case: subset of array (single-width slices)

The dimensionality of the http response from the server is somewhat non-intuitive,
so we need to test a case in which the single-width slices are dispersed:

```{r}
BR = getData(rd, list(c(4), 1:11, c(5), 1:3))
scs <- tuple(builtins$slice(3L, 4L, 1L), builtins$slice(0L, 12L, 1L),
             builtins$slice(4L, 5L, 1L), builtins$slice(0L, 3L, 1L))
BP <- pd$`__getitem__`(scs)
print(BR)
all(BP == BR)
```


```{r}
BR = getData(rd, list(c(5), 1:11, 1:7, c(2)))
scs <- tuple(builtins$slice(4L, 5L, 1L), builtins$slice(0L, 12L, 1L),
             builtins$slice(0L, 7L, 1L), builtins$slice(1L, 2L, 1L))
BP <- pd$`__getitem__`(scs)
print(BR)
all(BP == BR)
```



















